In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [34]:
!pip install panda
!pip install sklearn

In [35]:
iris = r'drive/My Drive/Kuis_DataMining/IRIS.csv'

In [36]:
import pandas as pd
data = pd.read_csv(iris)
data.head(5)

sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [61]:
data.columns.tolist()

['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'species']

In [62]:
import numpy as np

#Fitur yang akan diproses
fitur = data[['sepal_length', 'sepal_width', 'petal_length', 'petal_width']].to_numpy()
X = np.asarray(fitur)
X[0:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [63]:
#Label yang digunakan
y = data[['species']].values
y[0:10]

array([['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa']], dtype=object)

In [64]:
### merubah label pada species 
from sklearn import preprocessing
species = preprocessing.LabelEncoder()
species.fit(['Iris-setosa','Iris-versicolor','Iris-virginica'])
y = species.transform(y)

/usr/local/lib/python3.7/dist-packages/sklearn/preprocessing/_label.py:268: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [65]:
y[0:10]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [66]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=4)
print('Train set', X_train.shape, y_train.shape)
print('Test set', X_test.shape,y_test.shape)

Train set (120, 4) (120,)
Test set (30, 4) (30,)


In [67]:
### klasifikasi dengan svm
from sklearn import svm
svm1 = svm.SVC(kernel='rbf', gamma='auto')
svm1.fit(X_train,y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [68]:
from sklearn import svm
yhat = svm1.predict(X_test)
yhat [0:5]

array([2, 0, 2, 2, 2])

In [50]:
from sklearn import svm
yhat = svm1.predict(X_test)
yhat [0:5]

array([2, 0, 2, 2, 2])

In [60]:
import matplotlib.pyplot as plt
from sklearn.metrics import classification_report, confusion_matrix
cnf_matrix = confusion_matrix(y_test,yhat,labels=[0,1,2])
np.set_printoptions(precision=3)
print (classification_report(y_test,yhat))


              precision    recall  f1-score   support

           0       1.00      1.00      1.00        16
           1       1.00      0.80      0.89         5
           2       0.90      1.00      0.95         9

    accuracy                           0.97        30
   macro avg       0.97      0.93      0.95        30
weighted avg       0.97      0.97      0.97        30

